### ISSUE TITLE
Installation fails when /opt does not exists.

### ISSUE THREAD

**Issue by rudybroersma** [tedivm/puppet-rsnapshot#10]
When a node does not have the /opt directory, installation fails:

```
Error: Cannot create /opt/rsnapshot_wrappers; parent directory /opt does not exist

Error: /Stage[main]/Rsnapshot::Client::Wrappers/File[/opt/rsnapshot_wrappers]/ensure: change from absent to directory failed: Cannot create /opt/rsnapshot_wrappers; parent directory /opt does not exist
```

I will create a pull request to fix this, or add it in the awaiting pull request. Depends on who's first :

**Comment by rudybroersma** [comment]
This turns out to be a lot more difficult then I thought it would be. I'll give it another shot some other time.

**Comment by tedivm** [comment]
Why don't you just change the wrapper_path parameter for you setup and point it to a directory that does exist? You could also set something up to create "/opt" for you before running the rsnapshot module.

**Comment by rudybroersma** [comment]
Yes, ofcourse that would work. But we found a machine that didn't have the /opt dir, what causes the installation to fail and thus backups to fail as well. 

Creating /opt before running the module would also suffice, but I feel a solution that works for everyone is better. However, recursive create directories is a frequently asked feature in Puppet, and I thought I could script something. However, it seemed more difficult then I initially thought.

**Comment by tedivm** [comment]
What operating system or distro are you using that doesn't have opt? Typically speaking they'll have another directly they use for the same purpose. We can put that in to the params file to switch over to the other folder when on that OS.

**Comment by rudybroersma** [comment]
Its a regular Debian system, someone probably deleted it once. We only found this issue on one machine.

So its not related to a specific distribution/OS. 

Perhaps, as a " work around" instead of me trying to create something that recursively creates directories, we could perhaps check if /opt exists if the default installation path isnt changed by the Puppetmaster.

**Comment by tedivm** [comment]
I think that's a good plan for your systems. Since you've got admins who are erasing distro supplied directories you are likely to find other inconsistencies and problems with other modules as well, so putting something in your manifests to make sure that /opt exists on machines where it may have been deleted would resolve this problem for you.

**Comment by rudybroersma** [comment]
Alright. I understand you feel you dont want something that would recursivly create the directory tree. 
I can understand that, as this is not something Puppet does either.  I just thought it would be a nice addition.

In that case, we can close this issue I think.

**Comment by tedivm** [comment]
It's not so much that I don't want to create recursive directories (which is actually possible- I included an example below for you). I don't want to create directories that admins aren't aware of, and I don't want to be responsible for creating system directories which may require specific permissions that I would always have to account for. If a directory should exist on someone's system and it doesn't then there should be an error and they should investigate- if it's a minor thing they can fix it, but I don't want to mask a larger problem.

Here's a recursive directory resource you can use as a base if you need it.

``` puppet
define recursiveDirectory (
  $path = $name,
  $mode = '755'
){
  exec { "recursiveDirectory create directory $path":
    command: "mkdir -p -m $mode $path",
    creates: $path,
  }
}
```

**Comment by rudybroersma** [comment]
Well, if the directory doesn't exists already, the permissions shouldn't be an issue, correct?

But as I said, I understand your point of view.
