### ISSUE TITLE
Puppet 4 - Issues?

### ISSUE THREAD

**Issue by rudybroersma** [tedivm/puppet-rsnapshot#6]
First of all, thanks for this great plugin. It is very nice to be able to configure backups using Puppet this way. I managed to resolve some issues I encountered, but I feel there is an issue in the script. Perhaps this is only related to Puppet 4. I dont know, as I coulndgt get PuppetDB to work on 3.x

The issue is that all parameters that are configued as 'undef' in the manifests/param.pp are kept empty when Puppet compiles the configuration file. This for example results in a config file that has cmd_rsnapshot_diff, sync_first, linux_lvm_cmd_lvcreate etc without a value. Rsnapshot doesn't accept this and doesn't run.

I resolved this by editing the param.pp file, but I doubt this is the recommended solution.

**Comment by tedivm** [comment]
I'll have to try this out with puppet 4- we're still running 3 in house. Thanks for reporting.

**Comment by tedivm** [comment]
Should be resolved.
