### ISSUE TITLE
Small issue and question

### ISSUE THREAD

**Issue by rudybroersma** [tedivm/puppet-rsnapshot#7]
Hi,
- When the backup server doesn't have any keys (no /root/.ssh/id_xxx.pub) the backup obviously doesn't work. Perhaps the script could atleast report this or run ssh-keygen by itself.
- I seem to be unable to prevent creating cronjobs for schedules I dont want. I only want to run the weekly backups. I set retain_daily to 0, but this doesn't seem to do anything. Any tips on how I can achieve this? Now I get flooded by cronjob mails that rsnapshot cant run with a daily retention of 0.

**Comment by tedivm** [comment]
These are both good feature requests. When I get a chance I'll add these in, although if you'd like to you're welcome to give it a shot.
